server.port=8888
spring.application.name=config-server-book

spring.cloud.config.server.git.uri=https://github.com/SamyukthaaBalaji/bookstore-config.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true

